[mail.auth]
ident = ""
user = "darwinia-postman@yandex.com"
pass = "jlqjuuggzgxxappr"
host = "smtp.yandex.com"

[mail.msg]
addr = "smtp.yandex.com:587"
subject = "Subject: Darwinia Crashed ğŸ‘»ï¸ "
from = "Postman ğŸ§‘â€ğŸš€<darwinia-postman@yandex.com>"

[mailing]
list = [
     "clearloop@163.com",
     "weizhe.sun@itering.com",
]
